# Generated by Django 4.1 on 2022-09-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChannelData",
            fields=[
                ("channel_link", models.TextField(primary_key=True, serialize=False)),
                ("num_videos", models.BigIntegerField(default=0)),
                ("time_of_scrapping", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YoutubeScrappedData",
            fields=[
                ("video_link", models.TextField(primary_key=True, serialize=False)),
                ("author", models.CharField(default="", max_length=500)),
                ("title", models.CharField(default="", max_length=500)),
                ("likes", models.CharField(default="", max_length=20)),
                ("thumbnail", models.TextField(default="")),
                (
                    "channel_link",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scrap.channeldata",
                        verbose_name="channel_link",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commenter_name",
                    models.CharField(blank=True, default="Author", max_length=200),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "video_link",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scrap.youtubescrappeddata",
                        verbose_name="video_link",
                    ),
                ),
            ],
        ),
    ]
